name: IPFS Deploy (Staging)
on:
  push:
    paths:
      - 'www/**'
      - 'data/**'
      - '.github/workflows/**'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install dependencies
        run: cd www && deno install --allow-scripts
      - uses: actions/cache@v4
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deps.ts') }}

      - name: Build website
        run: |
          cd www
          lume build
  
      - name: Deploy to Storacha with Blumen
        run: |
          output=$(deno -A npm:blumen deploy ./www/_site)
          echo "$output"
          cid=$(echo "$output" | grep -oP 'Root CID: \K\S+')
          echo "CID=$cid" >> $GITHUB_OUTPUT
        env:
          BLUMEN_STORACHA_PROOF: ${{ secrets.BLUMEN_STORACHA_PROOF }}
          BLUMEN_STORACHA_TOKEN: ${{ secrets.BLUMEN_STORACHA_TOKEN }}